name: hsxo
version: 0.1.0.0
github: "nsychev/hsxo"
license: "AGPL-3"
author: "Nikita Sychev"
maintainer: "root@nsychev.ru"
copyright: "2020 Nikita Sychev"
description: "<https://github.com/nsychev/hsxo#readme>"
dependencies:
- async
- base >= 4.7 && < 5
- cereal
- microlens
- mtl
- network
- protobuf
- random
- utf8-string

library:
  source-dirs: src
executables:
  hsxo-server:
    main: Main.hs
    source-dirs: server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsxo
  hsxo-client:
    main: Main.hs
    source-dirs: client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsxo
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hspec
    - hsxo
